/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// Use environment variables for dynamic configuration
const awsmobile = {
    "aws_project_region": process.env.NEXT_PUBLIC_AWS_REGION || "eu-west-2",
    "aws_appsync_graphqlEndpoint": process.env.NEXT_PUBLIC_AWS_APPSYNC_GRAPHQL_ENDPOINT || "https://54ofumz56bfh3kozn2qrd55ih4.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": process.env.NEXT_PUBLIC_AWS_APPSYNC_REGION || "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": process.env.NEXT_PUBLIC_AWS_APPSYNC_API_KEY || "da2-2ottpnk4ejdarf3moy2nzq2adu",
    "aws_cognito_identity_pool_id": "eu-west-2:TBD",
    "aws_cognito_region": process.env.NEXT_PUBLIC_AWS_REGION || "eu-west-2",
    "aws_user_pools_id": process.env.NEXT_PUBLIC_AWS_USER_POOLS_ID || "eu-west-2_VvBB48LmX",
    "aws_user_pools_web_client_id": process.env.NEXT_PUBLIC_AWS_USER_POOLS_WEB_CLIENT_ID || "3843f0u00360rit8kml02ll07j",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": process.env.AWS_USER_FILES_S3_BUCKET || "prorecruit-storage-eu-west-2-624914081304",
    "aws_user_files_s3_bucket_region": process.env.NEXT_PUBLIC_AWS_REGION || "eu-west-2"
};


export default awsmobile;
